export class DiarioMovil{
  constructor(
    public  id?: number,
    public  instructorId?: string,
    public  combustible?: string,
    public  desperfecto?:string,
    public  fechaCreacion?: Date,
    public  lucesDelanterasCortasIzquierda?: string,
    public  lucesDelanterasLargasIzquierda?: string,
    public  lucesDelanterasSenialeroIzquierdo?: string,
    public  lucesDelanterasCortasDerecha?: string,
    public  lucesDelanterasLargasDerecha?: string,
    public  lucesDelanterasSenialeroDerecho?: string,
    public  lucesTracerasPosicionIzquierda?: string,
    public  lucesTracerasPosicionDerecha?: string,
    public  lucesTracerasSenialeroIzquierdo?: string,
    public  lucesTracerasSenialeroDerecho?: string,
    public  lucesTracerasReversa?: string,
    public  lucesTracerasFreno?: string,
    public  movilId?: number,
    public  movilKilometraje?: number,
    public  nivelAgua?: string,
    public  nivelAceite?: string,
    public  objetoAuxiliar?: string,
    public  objetoBaliza?: string,
    public  objetoExtintor?: string,
    public  objetoConos?: string,
    public  observaciones?: string,
  ){}
}
