import { ProgresoInicial } from '../enums/progreso-inicial.enum';
import { ProgresoAlumno } from '../enums/progreso-alumno.enum';
import { ProgresoManiobras } from '../enums/progreso-maniobras.enum';

export class EvaluacionAlumno{
  constructor(
    public id?: number,
    public alumnoNombreApellido?: string,
    public aceptaIndicacionesInstructor?: ProgresoAlumno,
    public circulaManteniendoDerecha?: ProgresoAlumno,
    public dominaUsoPedales?: ProgresoAlumno,
    public dominaAdministracionCambios?: ProgresoAlumno,
    public dominaUsoEspejos?: ProgresoAlumno,
    public dominaVehiculoEnRepecho?: ProgresoAlumno,
    public evaluaEnfrentaAdecuadamenteDificultades?: ProgresoAlumno,
    public escInsId?: string,
    public estacionamientoLateralDerecho?: ProgresoManiobras,
    public estacionamientoLateralIzquierdo?: ProgresoManiobras,
    public estacionamient45GradosDerecho?: ProgresoManiobras,
    public estacionamient45GradosIzquierdo?: ProgresoManiobras,
    public frenaConSuficienteAnticipacion?: ProgresoAlumno,
    public fechaCreacion?: Date,
    public giroUbicacionCorrectamente?: ProgresoAlumno,
    public giroSenializaCorrectamente?: ProgresoAlumno,
    public giroIngresaCorrectamenteNuevaVia?: ProgresoAlumno,
    public giroVelocidadCorrecta?: ProgresoAlumno,
    public mantieneDistanciaSeguridad?: ProgresoAlumno,
    public mantieneVelocidadAdecuada?: ProgresoAlumno,
    public marchaAtras?: ProgresoManiobras,
    public numeroClase?: number,
    public observaciones?: string,
    public progresoEnciendeVehiculo?: ProgresoInicial,
    public progresoMarchaVehiculo?: ProgresoInicial,
    public progresoEncendidoEnNeutro?: ProgresoInicial,
    public reconoceSentidosCirculacion?: ProgresoAlumno,
    public respetaTodasSenialesTransito?: ProgresoAlumno,
    public respetaSendasPeatonales?: ProgresoAlumno,
    public respetaOtrosUsuariosDeLaVia?: ProgresoAlumno,
    public seguridadCinturon?: ProgresoAlumno,
    public seguridadRegulaButacaApoyaCabezas?: ProgresoAlumno,
    public seguridadRegulaEspejos?: ProgresoAlumno,
    public senializaCorrectamenteCambioCarril?: ProgresoAlumno,
    public senializaManiobrasARealizar?: ProgresoAlumno,
    public saleConduciendoACU?: ProgresoAlumno,
    public slalom?: ProgresoManiobras,
    public tieneBuenaTecnicaBrazos?: ProgresoAlumno,
    public toleranciaStressTransito?: ProgresoAlumno,
    public vuelveConduciendoACU?: ProgresoAlumno,
  ){}
}
